
version: '3.7'

services:
    springproject:
        build:
            context: .
            dockerfile: Dockerfile.nextjs
        image: nextjs_blue:0.1
        ports: 
            - "3001:3000"
        container_name: nextjs_blue