
version: '3.7'

services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile.nextjs
        image: nextjs_blue:0.1
        ports: 
            - "3001:3000"
        container_name: nextjs_blue
        deploy:
            resources:
                limits:
                    cpus: '0.001'
                    memory: 50M
                reservations:
                    cpus: '0.0001'
                    memory: 20M
