
version: '2.4'

services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile.nextjs
        image: nextjs_blue:0.1
        ports: 
            - "3001:3000"
        container_name: nextjs_blue
        mem_limit: 50m
        mem_reservation: 20M
        cpus: 0.001
